[tool.poetry]
name = "django3.0-graphql-subscriptions"
version = "0.1.0"
description = ""
authors = ["Jayden Windle <jaydenwindle@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
django = "^3.0"
channels = "^2.3"
django-extensions = "^2.2"
graphene-django = "^2.7"
channels_redis = "^2.4"
pytest = "^5.3"
pytest-asyncio = "^0.10.0"
pytest-django = "^3.7"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
