name: Test Package
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
    - uses: dschep/install-poetry-action@v1.2
    - run: poetry run pytest --cov=src --cov-branch --cov-fail-under=50 tests/