name: Test Package
on: push

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
    - run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - run: $HOME/.poetry/bin/poetry run pytest --cov=src --cov-branch --cov-fail-under=50 tests/